/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>

//For RCC
#define RCC_BASE_ADDR                 0x40023800UL

#define RCC_RCC_CFGR_OFFSET           0x08 //(MCO1) OFFSET
#define RCC_RCC_CFGR_ADDR             (RCC_BASE_ADDR + RCC_RCC_CFGR_OFFSET)

#define RCC_AHB1ENR_OFFSET            0x30 //AHB1 BUS ENABLE FOR GPIOA PERIPHERAL
#define RCC_AHB1ENR_ADDR              (RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)

//For GPIOA
#define GPIOA_BASE_ADDR               0x40020000UL
#define GPIOx_MODER_OFFSET            0x00
#define GPIOA_MODER_ADDR              (GPIOA_BASE_ADDR + GPIOx_MODER_OFFSET)

//GPIO alternate function high register (GPIOx_AFRH)
#define GPIOx_AFRH_OFFSET             0x24
#define GPIOx_AFRH_ADDR               (GPIOA_BASE_ADDR + GPIOx_AFRH_OFFSET)


int main(void)
{

	//Enable RCC for MCO1
	uint32_t *pRCC_cfgr_regAddr = (uint32_t*) RCC_RCC_CFGR_ADDR;
	*pRCC_cfgr_regAddr &= ~(3 << 21);

	//Prescaler for MCO1
	*pRCC_cfgr_regAddr &= ~(7 << 24);//clearing bit pos 24,25,26
	*pRCC_cfgr_regAddr |=  (6 << 24);//setting (dividing by 4 as (6hex = 110) = i.e dividing by 4)i.e (16MHZ/4 = 4MHZ)

	//configure PA8 as alternate function for MCO1 according to data sheet
	//1. enable RCC for portA
	uint32_t *pRCC_Ahb1Enr_regAddr = (uint32_t *)RCC_AHB1ENR_ADDR;
	*pRCC_Ahb1Enr_regAddr |= (1 << 0);//Enable GPIOA peripheral clock


	//2.configure the mode of GPIO pin8 as alternate function mode
	uint32_t *pGpioA_reg_Addr = (uint32_t *)GPIOA_MODER_ADDR;
	*pGpioA_reg_Addr &= ~(3 << 16);//clearing
	*pGpioA_reg_Addr |=  (2 << 16);//setting PA8 as alternate function


	//3. configure the alternation function register to set the mode 0 for PA8
	uint32_t *pGpioAFRH_reg_Addr = (uint32_t *)GPIOx_AFRH_ADDR;
	*pGpioAFRH_reg_Addr &= ~(0xf << 0);

    /* Loop forever */
	for(;;);
}
